apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.metadata.name }}
spec:
  kafka:
    version: {{ .Values.kafka.version }}
    replicas: {{ .Values.kafka.replicas }}
    listeners:
      {{- toYaml .Values.kafka.listeners | nindent 6 }}
    config:
      {{- toYaml .Values.kafka.config | nindent 6 }}
    storage:
      type: {{ .Values.kafka.storage.type }}
    {{- if .Values.kafka.metricsConfig }}
    metricsConfig:
      type: {{ .Values.Kafka.MetricsConfig.Type }}
      valueFrom:
        configMapKeyRef:
          name: {{ .Values.Kafka.MetricsConfig.ValueFrom.ConfigMapKeyRef.Name }}
          key: {{ .Values.Kafka.MetricsConfig.ValueFrom.ConfigMapKeyRef.Key }}
    {{- end }}
  zookeeper:
    replicas: {{ .Values.zookeeper.replicas }}
    storage:
      type: {{ .Values.zookeeper.storage.type }}
    {{- if .Values.zookeeper.metricsConfig }}
    metricsConfig:
      type: {{ .Values.Zookeeper.MetricsConfig.Type }}
      valueFrom:
        configMapKeyRef:
          name: {{ .Values.Zookeeper.MetricsConfig.ValueFrom.ConfigMapKeyRef.Name }}
          key: {{ .Values.Zookeeper.MetricsConfig.ValueFrom.ConfigMapKeyRef.Key }}
    {{- end }}
  entityOperator:
    topicOperator: {}
    userOperator: {}
  {{- if .Values.kafkaexporter}}
  kafkaExporter:
    topicRegex: {{ .Values.kafkaExporter.topicRegex }}
    groupRegex: {{ .Values.kafkaExporter.groupRegex }}
  {{- end }}